
[package]
name = "ni"
version = "0.1.0"
authors = ["C-Radius <deus.deceit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
image = "0.24.5"
